Shopify/prettier-plugin-liquid

grammar/liquid-html.ohm, src/parser/ast.spec.ts, src/parser/ast.ts, src/parser/cst.spec.ts, src/parser/cst.ts, src/printer/preprocess/augment-with-css-properties.ts, src/printer/print/liquid.ts, src/printer/printer-liquid-html.ts, src/types.ts, test/liquid-tag-assign/fixed.liquid, test/liquid-tag-assign/index.liquid, test/liquid-tag-assign/index.spec.ts, test/liquid-tag-echo/fixed.liquid, test/liquid-tag-echo/index.liquid, test/liquid-tag-echo/index.spec.ts, test/whitespace-trim-on-liquid-tag-break/fixed.liquid, test/whitespace-trim-on-liquid-tag-break/index.liquid
- Minor refactor of liquidTag ohm rule to be open for extension
- Add pretty printing of the `echo` liquid tag
- Add pretty printing of the `assign` tag
- `echo` tag
- print tag name and variable expression on the same line as the opening `{%`
- break and indent filters (if necessary)
- `%}` on an empty line (if breaking)
- `assign` tag
- print tag name, variable name, '=', and variable expression on the same line as the opening `{%`
- break and indent filters (if necessary)
- `%}` on an empty line (if breaking)
- [example from Dawn](https://github.com/Shopify/dawn/compare/wip%2Fprettier...Shopify:wip%2Fprettier-2#diff-f38ed67a42b1f5bee67cf7ed5873cf1839d3e83f21848da0c327078dffe47de0R616-R618)
As per #13 and #23, it looks like we want indented args. Also It looks like we want tags to …
=> Add proper support of `assign` and `echo` tags

grammar/liquid-html.ohm, src/parser/ast.ts, src/parser/cst.ts, src/printer/print/liquid.ts, test/liquid-tag-section/fixed.liquid, test/liquid-tag-section/index.liquid, test/liquid-tag-section/index.spec.ts
- Print section tag as `{% section $string %}`
- Strips superfluous whitespace
- Adds missing whitespace
- Respects liquidSingleQuote
Fixes #59
=> Add proper support for `section` tag

grammar/liquid-html.ohm, src/parser/ast.spec.ts, src/parser/ast.ts, src/parser/cst.spec.ts, src/parser/cst.ts, src/printer/preprocess/augment-with-css-properties.ts, src/printer/print/liquid.ts, src/printer/printer-liquid-html.ts, src/types.ts, test/liquid-tag-elsif/fixed.liquid, test/liquid-tag-elsif/index.liquid, test/liquid-tag-elsif/index.spec.ts, test/liquid-tag-if/fixed.liquid, test/liquid-tag-if/index.liquid, test/liquid-tag-if/index.spec.ts
- Prevent liquidVariableLookup from matching on empty string
- Add support for `if` and `unless` tags
- Add support for `elsif` tag
- `{% if $firstCondition` on first line
- maybe break other conditions on new lines (with logical operator on the new line)
- maybe break comparator on new lines
- `%}` on new line if breaking
```liquid
It should break before comparators (and indent)
printWidth: 1
{% if lower
< some.variable
and some.variable
< upper
%}
hello
{% endif %}
It should try to keep comparators on same line
printWidth: 30
{% if lower < some.variable
and some.variable < upper
%}
hello
{% endif %}
It should support all kinds of shit
printWidth: 30
{% if false %}
{% elsif lower < some.variable
and some.variable < upper
and string contains 'hi'
or string == empty
or nil
or var.lookup
%} …
```
=> Add support for `if`, `elsif` and `unless` tags

grammar/liquid-html.ohm, src/parser/ast.spec.ts, src/parser/ast.ts, src/parser/cst.spec.ts, src/parser/cst.ts, src/printer/print/liquid.ts, src/types.ts, test/liquid-tag-case/fixed.liquid, test/liquid-tag-case/index.liquid, test/liquid-tag-case/index.spec.ts
- Add support for `case` tag
- Add support for `when` tag
- Never break `case`
- Only break `when` when the undocumented comma or `or` syntax is used
- Same way as the others
```liquid
It should break and indent when statements, and not break the when
printWidth: 1
{% case candy.type %}
{% when 'gummy bears' %}
yum!
{% else %}
ok!
{% endcase %}
It should break on when comma syntax
printWidth: 1
{% case candy.type %}
{% when 'gummy bears',
'chocolate'
%}
yum!
{% else %}
ok!
{% endcase %}
It should break on when or syntax (and prefer commas)
printWidth: 1
{% case candy.type %}
{% when 'gummy bears',
'chocolate',
'chips'
%}
yum!
{% else %}
ok!
{% endcase %}
```
=> Add support for `case` and `when` tags

grammar/liquid-html.ohm, src/parser/ast.ts, src/parser/cst.spec.ts, src/parser/cst.ts, src/printer/preprocess/augment-with-css-properties.ts, src/printer/print/liquid.ts, src/printer/printer-liquid-html.ts, src/types.ts, test/liquid-tag-for/fixed.liquid, test/liquid-tag-for/index.liquid, test/liquid-tag-for/index.spec.ts, test/liquid-tag-tablerow/fixed.liquid, test/liquid-tag-tablerow/index.liquid, test/liquid-tag-tablerow/index.spec.ts
- Add support for the `for` tag
- Add support for `tablerow` tag
- Asked the partner slack and it looks like we only want to break after `for x in col` (unanimously)
- Break after `{% $tag x in collection`
- if there's `reversed` or there are tag arguments
- `%}` on new line for consistency
```liquid
It breaks on both reversed and tag arguments
printWidth: 1
{% for element in collection
reversed
limit: 10
%}
{{ element }}
{% endfor %}
It only breaks if the printWidth is hit
printWidth: 80
{% for element in collection reversed limit: 10 %}
{{ element }}
{% endfor %}
```
Fixes #64
=> Add support for `for` and `tablerow` tags

grammar/liquid-html.ohm, src/parser/ast.ts, src/parser/cst.ts, src/printer/print/liquid.ts, src/types.ts, test/liquid-tag-layout/fixed.liquid, test/liquid-tag-layout/index.liquid, test/liquid-tag-layout/index.spec.ts
Same as `section` tag.
Only one arg, but it's a `liquidExpression` this time.
Fixes #65
=> Add support for `layout` tag

grammar/liquid-html.ohm, src/parser/ast.ts, src/parser/cst.spec.ts, src/parser/cst.ts, src/printer/preprocess/augment-with-css-properties.ts, src/printer/print/liquid.ts, src/printer/printer-liquid-html.ts, src/types.ts, test/liquid-tag-cycle/fixed.liquid, test/liquid-tag-cycle/index.liquid, test/liquid-tag-cycle/index.spec.ts
- Add support for the `cycle` tag
- Print `{% cycle` or `{% cycle $groupName:}` on the first line
- Maybe break list of items
- `%}` on new line if broken
```liquid
{% # printWidth: 1 %}
{% cycle
'one',
'two'
%}
{% # or %}
{% cycle groupName:
'one',
'two'
%}
```
Fixes #68
=> Add support for the `cycle` tag

grammar/liquid-html.ohm, src/parser/ast.ts, src/parser/cst.spec.ts, src/parser/cst.ts, src/printer/print/liquid.ts, src/types.ts, test/liquid-tag-capture/fixed.liquid, test/liquid-tag-capture/index.liquid, test/liquid-tag-capture/index.spec.ts
This does not fixes the capture body issue. It looks like that's broken
but I'll fix it in a different PR and handle it the same way I'd handle
`raw` I think.
As for the tag name markup, rule is simple: don't break it.
Fixes #67
=> Add support for the `capture` open tag parsing

src/printer/print/children.ts, src/printer/utils/node.ts, test/liquid-prettier-ignore/fixed.liquid, test/liquid-prettier-ignore/index.liquid, test/liquid-prettier-ignore/index.spec.ts, test/test-helpers.ts
Turns out we already support #47
Fixes #47
=> Add support for `{% # prettier-ignore %}`

grammar/liquid-html.ohm, src/parser/ast.ts, src/parser/cst.spec.ts, src/parser/cst.ts, src/printer/preprocess/augment-with-css-properties.ts, src/printer/printer-liquid-html.ts, src/types.ts, test/html-doctype/fixed.liquid, test/html-doctype/index.liquid, test/html-doctype/index.spec.ts
For html5 doctypes, prefer the lowercase version. For other versions, we'll just paste the source as is.
Fixes #96
=> Add proper support for HTML doctypes

grammar/liquid-html.ohm, src/parser/cst.spec.ts, src/parser/cst.ts, test/liquid-comment/fixed.liquid, test/liquid-comment/index.liquid, test/liquid-liquid-tag/fixed.liquid, test/liquid-liquid-tag/index.liquid
Fixes #74
The language allows us to do this (for convenience). This PR adds fixes support for that.
The technique used is a bit similar to the one I used for Syntax
Highlighting.
A "comment" block was considered a "raw" tag block. We'd parse it like this:
- match `/{%-?\s*comment\s*-?%}/`
- that's the `.blockStart` of the tag
- match all characters until one that is _followed_ by `/{%-?\s*endcomment\s*-?%}/`
- that's the `body` of the tag
- match `/{%-?\s*endcomment\s*-?%}/`
- that's the `.blockEnd` of the tag
This approach _didn't_ work for nested tags, since we'd match over the `{% comment %}` of the nested comment and stop at the `{% endcomment %}` of the nested comment. Leaving us with a dangling comment body and `{% endcomment %}`.
Something like this:
```liquid
{% comment %}
This is …
```
=> Add support for nested block comments

grammar/liquid-html.ohm, src/parser/ast.ts, src/parser/cst.ts, src/printer/print/liquid.ts, test/embed-liquid-stylesheet-tag/fixed.liquid, test/embed-liquid-stylesheet-tag/index.liquid, test/embed-liquid-stylesheet-tag/index.spec.ts, test/liquid-tag-string-fallback/fixed.liquid
Last week I learned [`{% style %}`](https://shopify.dev/api/liquid/tags#style) != [`{% stylesheet %}`](https://shopify.dev/themes/architecture/sections/section-assets#stylesheet) in Liquid.
The output is different, but their API is the same: they both take CSS as body.
In this PR:
- Duplicate the support we have for the `style` tag with `stylesheet`
- Prevent parsing collision of `{%schema-%}` since `-` is an identifier character.
- Prevent parsing collision of `{% style %}` and `{% stylesheet %}` since `s` is an identifier character.
Fixes #116
=> Add support for the `stylesheet` tag

src/parser/index.ts, src/parser/parser.ts, src/parser/stage-1-cst.spec.ts, src/parser/stage-1-cst.ts, src/parser/stage-2-ast.spec.ts, src/parser/stage-2-ast.ts, src/printer/print-preprocess.ts, src/printer/print/liquid.ts, src/types.ts
- Renames (objective make the flow more obvious)
- `cst.ts` -> `stage-1-cst.ts`,
- `ast.ts` -> `stage-2-ast.ts`
- Add explainer comments at head of both files
- Make the CST responsible for setting `.source` on the nodes
- Cleans up wiring of `source` argument in all the methods in `stage-2-ast.ts`
=> Internal refactor of parser pipeline

.prettierrc.json, src/printer/print/tag.ts, test/issue-120/fixed.liquid, test/issue-120/index.liquid, test/issue-120/index.spec.ts
We have a special rule to prevent awkward multiline breaks, this doesn't
play well when the input already was multilne.
Fixes #120
=> Fix the rendering of html tags with one attribute that is multiline

README.md, grammar/liquid-html.ohm, src/parser/grammar.spec.ts, src/printer/print/tag.ts, src/printer/printer-liquid-html.ts, src/printer/utils/node.ts, test/issue-123/fixed.liquid, test/issue-123/index.liquid, test/issue-123/index.spec.ts, test/prettier-ignore-attribute/fixed.liquid, test/prettier-ignore-attribute/index.liquid, test/prettier-ignore-attribute/index.spec.ts
- Document how to ignore nodes with `prettier-ignore` and `prettier-ignore-attributes`
- Fixup support for `prettier-ignore-attributes`
- Be less picky about `anyExcept` rule in attributes. `[[/if` should parse just fine.
Fixes #123
=> Add support for `prettier-ignore-attributes` and fix secondary templating parsing issue

test/embed-liquid-style-tag/fixed.liquid, test/embed-liquid-style-tag/index.liquid
No change of functionality, verifies an [issue](https://github.com/Shopify/dawn/pull/2126#discussion_r1023237668) raised in Dawn. 
Fixes #119
=> Add unit tests for weird `{% style %}` tag reformating

grammar/liquid-html.ohm, src/parser/grammar.spec.ts, src/parser/stage-1-cst.ts
This is a weird parsing ambiguity problem.
Before, our rule was the following:
```
identifierCharacter = alnum | "_" | "-"
liquidTagBaseCase = "{%" space* (tagName ~identifierCharacter) space* tagMarkup "-"? "%}"
```
Our problem was that `-` is both an identifier character and the character we use for stripping whitespace from the end of tags and variable output (`-%}` and `-}}`).
So `{% else-%}` threw an error because `tagName` _was_ followed by `-`, which is an identifier character.
The solution is to change that rule to the following:
- Followed by an "end of tag" `-}}`, `-%}`, OR
- Not followed by an identifierCharacter
Fixes #126
=> Fixup parsing of `{% else-%}`

grammar/liquid-html.ohm, src/parser/grammar.spec.ts, src/parser/stage-1-cst.spec.ts, src/parser/stage-1-cst.ts, src/parser/stage-2-ast.spec.ts, src/parser/stage-2-ast.ts, src/printer/preprocess/augment-with-whitespace-helpers.ts, src/printer/printer-liquid-html.ts, test/html-attributes/fixed.liquid, test/html-attributes/index.liquid
Examples:
```liquid
{% # AttrDoubleQuoted with Liquid in attribute name %}
<a data-popup--{{ section.id }}="placeholder">
{% # AttrEmpty with Liquid in attribute name %}
<a data-popup--{{ section.id }}>
```
In this PR:
- Change the Ohm parsing rule for `attrName` from `attrNameTextNode` to `(liquidDrop | attributeNameTextNode)*`
- Change the CST `AttributeNode.name` type from `string` to `(string | ConcreteLiquidDrop)[]`
- Change the AST `AttributeNode.name` type from `string` to `(string | LiquidDrop)[]`
- Change the printing rules for `AttributeNode` to ≈ `join('', attr.name.map(print))`;
Fixes #101
=> Allow for liquid output in attribute names

grammar/liquid-html.ohm, src/parser/stage-1-cst.spec.ts, test/html-attributes/fixed.liquid, test/html-attributes/index.liquid
e.g. parse the following as though the quotes were the correct ones
```liquid
<h1 class=“section-header__title h2” id=‘abc’></h1>
```
and reprint as dumb quotes
```liquid
<h1 class="section-header__title h2" id="abc"></h1>
```
Fixes #130
=> Parse smart quotes as dumb quotes to prevent formatted copy pasting errors

src/parser/stage-2-ast.spec.ts, src/parser/stage-2-ast.ts, src/printer/printer-liquid-html.ts, src/types.ts, test/liquid-tag-no-argument/fixed.liquid, test/liquid-tag-no-argument/index.liquid
- Refactor duplicated nonTraversableProperties
- Top level unclosed tags should throw errors
=> Unclosed AST should throw a LiquidHTMLParsingError

src/parser/stage-2-ast.spec.ts, src/parser/stage-2-ast.ts
Avoid undefined 'undefined' messages as per #138.
Fixes #138
=> Fix parsing error messages

.github/workflows/add-prettier-plugin-liquid-issues-to-theme-developer-tools-project.yml, .github/workflows/add_prettier_plugin_liquid_issues_to_theme_developer_tools_project.yml
Introduce GitHub action to auto add issues to the Theme Developer Tools project.
Requires https://github.com/Shopify/github-actions-access-provider/pull/607
=> Introduce action to auto add issues to the Theme Developer Tools project

grammar/liquid-html.ohm, src/parser/grammar.spec.ts, src/parser/grammar.ts, src/parser/stage-1-cst.spec.ts, src/parser/stage-1-cst.ts, src/parser/stage-2-ast.ts
`toLiquidHtmlAST` and `toLiquidAST` now both accept the `{ mode: 'completion' }` option.
This lets us add █ characters in places where it would otherwise be impossible to "partially" parse.
Stuff like the following will be parseable:
- `{% █ %}`,
- `{{ █ }}`,
- `{{ var.█ }}`,
- `{{ var[█] }}`,
- `{{ var | █ }}`,
- `{{ var | replace: █ }}`.
Which will empower us to complete those areas without having a partial string to complete.
=> Add completion mode

.github/workflows/ci.yml, .husky/pre-commit, .mocharc.json, README.md, package.json, src/index.ts, src/parser/index.ts, src/parser/parser.ts, src/parser/stage-1-cst.ts, src/printer/embed.ts, src/printer/index.ts, src/printer/preprocess/augment-with-whitespace-helpers.ts, src/printer/print/children.ts, src/printer/print/element.ts, src/printer/print/liquid.ts, src/printer/print/tag.ts, src/printer/printer-liquid-html.ts, src/types.ts, test/test-helpers.ts, test/test-setup.js, yarn.lock
We still support prettier2, but we now accept prettier3 as a peer dependency as well.
Fixes #87
Fixes #194
=> Add support for prettier 3
